# Generated by Django 4.1.7 on 2023-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='courses',
            field=models.ManyToManyField(related_name='achievements', to='base.course'),
        ),
    ]
