# Generated by Django 4.1.7 on 2023-05-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_question_remove_achievement_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='achievement',
        ),
    ]
