# Generated by Django 4.1.7 on 2023-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_question_answer_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='otvet',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='vopros',
            field=models.TextField(default=''),
        ),
    ]
