# Generated by Django 4.1.7 on 2023-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_courseresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('R', 'Radio'), ('C', 'Checkbox'), ('T', 'Text')], max_length=1),
        ),
    ]
