# Generated by Django 4.1.7 on 2023-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.CharField(choices=[('2', 'Два варианта ответов'), ('3', 'Три варианта ответов'), ('4', 'Четыре варианта ответов')], default='2', max_length=1),
        ),
    ]
