# Generated by Django 4.1.7 on 2023-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_test_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
