# Generated by Django 4.1.7 on 2023-05-15 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0022_remove_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='topic',
        ),
        migrations.CreateModel(
            name='BigCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='bigcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bigcourse'),
        ),
    ]
