# Generated by Django 4.1.7 on 2023-05-15 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_course_topic_bigcourse_course_bigcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bigcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bigcourse'),
        ),
    ]
