# Generated by Django 4.1.7 on 2023-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_question_bigcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigcourse',
            old_name='progress',
            new_name='full_progress',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='progress',
            new_name='full_progress',
        ),
        migrations.AddField(
            model_name='bigcourse',
            name='min_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='min_progress',
            field=models.IntegerField(default=0),
        ),
    ]
