# Generated by Django 4.1.7 on 2023-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_full_progress_course_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_progress',
            field=models.IntegerField(default=0),
        ),
    ]
