# Generated by Django 4.1.7 on 2023-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcourse',
            name='course_count',
            field=models.IntegerField(default=0),
        ),
    ]
